(()=>{
const $=id=>document.getElementById(id);let key=sessionStorage.getItem('site-admin-key')||'';let items=[];let settings={seo:{},site:{}};const frame=$('preview');
function showApp(){ $('login').hidden=true;$('app').hidden=false;load() }
$('loginBtn').onclick=()=>{key=$('key').value.trim();if(!key)return;$('loginBtn').disabled=true;load(true).finally(()=>{$('loginBtn').disabled=false})};if(key)showApp();
async function load(fromLogin=false){try{const r=await fetch('/api/site-settings',{cache:'no-store'});settings=await r.json()||{seo:{},site:{}};sessionStorage.setItem('site-admin-key',key);if(fromLogin){showApp();return}bindMeta();await waitFrame();items=frame.contentWindow.SiteContent?.collect?.()||[];mergeSaved();render();$('status').textContent=`Sanity · ${items.length} elemente`;$('count').textContent=`${items.length} fusha`}catch(e){$('status').textContent='Nuk u ngarkua përmbajtja.'}}
function waitFrame(){return new Promise(resolve=>{if(frame.contentDocument?.readyState==='complete'&&frame.contentWindow.SiteContent)return resolve();frame.addEventListener('load',resolve,{once:true})})}
function mergeSaved(){const saved=new Map((settings.contentItems||[]).map(i=>[i.key,i]));items=items.map(i=>saved.has(i.key)?{...i,value:saved.get(i.key).value,label:saved.get(i.key).label||i.label,section:saved.get(i.key).section||i.section}:i)}
function bindMeta(){const s=settings.seo||{};$('seoTitle').value=s.title||'';$('seoDescription').value=s.description||'';$('canonical').value=s.canonicalUrl||'';$('ogTitle').value=s.ogTitle||'';$('ogDescription').value=s.ogDescription||'';$('twitterTitle').value=s.twitterTitle||'';$('twitterDescription').value=s.twitterDescription||''}
function updatePreview(){frame.contentWindow.SiteContent?.apply?.({...settings,contentItems:items})}
function render(){const q=($('search').value||'').toLowerCase();const box=$('fields');box.replaceChildren();items.forEach((item,i)=>{if(q&&!`${item.label} ${item.section} ${item.value}`.toLowerCase().includes(q))return;const wrap=document.createElement('div');wrap.className='field';const label=document.createElement('label');label.textContent=item.label||item.key;const sec=document.createElement('span');sec.className='section';sec.textContent=item.section||'global';label.append(sec);const area=document.createElement('textarea');area.value=item.value||'';area.dataset.i=i;area.addEventListener('input',()=>{items[i].value=area.value;updatePreview()});wrap.append(label,area);box.append(wrap)});$('count').textContent=`${items.length} fusha`}
$('search').addEventListener('input',render);['seoTitle','seoDescription','canonical','ogTitle','ogDescription','twitterTitle','twitterDescription'].forEach(id=>$(id).addEventListener('input',()=>{settings.seo=settings.seo||{};const map={seoTitle:'title',seoDescription:'description',canonical:'canonicalUrl',ogTitle:'ogTitle',ogDescription:'ogDescription',twitterTitle:'twitterTitle',twitterDescription:'twitterDescription'};settings.seo[map[id]]=$(id).value;updatePreview()}));
$('importBtn').onclick=()=>{items=frame.contentWindow.SiteContent?.collect?.()||[];render();updatePreview();$('status').textContent=`U importuan ${items.length} elemente. Kliko Ruaj në Sanity.`};
$('saveBtn').onclick=async()=>{const btn=$('saveBtn');btn.disabled=true;btn.textContent='Po ruhet…';try{const payload={seo:settings.seo||{},site:settings.site||{},contentItems:items};const r=await fetch('/api/admin-site-settings',{method:'POST',headers:{'Content-Type':'application/json','x-admin-key':key},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Save failed');settings.contentItems=items;localStorage.setItem('site-settings-saved',Date.now());$('status').textContent='✓ U ruajt në Sanity';}catch(e){$('status').textContent=e.message==='Unauthorized'?'ADMIN_KEY i gabuar ose mungon në Vercel.':`Gabim: ${e.message}`}finally{btn.disabled=false;btn.textContent='Ruaj në Sanity'}};
frame.addEventListener('load',()=>{setTimeout(()=>{if(!$('app').hidden){items=frame.contentWindow.SiteContent?.collect?.()||items;mergeSaved();render();updatePreview()}},250)});
})();
