(()=>{
const ADMIN_EMAIL='shabankrasniqifizoterapi@gmail.com';
const $=id=>document.getElementById(id);let key=sessionStorage.getItem('site-admin-key')||'';let items=[];let settings={seo:{},site:{}};const frame=$('preview');
const loadScript=src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=true;s.crossOrigin='anonymous';s.onload=resolve;s.onerror=()=>reject(new Error('ClerkJS nuk mund të ngarkohet'));document.head.append(s)});
function setGate(message,allowed=false){$('clerkStatus').textContent=message;if(allowed){$('clerkGate').hidden=true;$('login').hidden=false}else{$('login').hidden=true;$('app').hidden=true}}
async function initClerk(){try{const r=await fetch('/api/clerk-config',{cache:'no-store'}),cfg=await r.json();if(!r.ok||!cfg.publishableKey)throw Error(cfg.error||'Clerk nuk është konfiguruar');const domain=atob(cfg.publishableKey.split('_')[2]).slice(0,-1);await loadScript(`https://${domain}/npm/@clerk/ui@1/dist/ui.browser.js`);await loadScript(`https://${domain}/npm/@clerk/clerk-js@6/dist/clerk.browser.js`);await Clerk.load({ui:{ClerkUI:window.__internal_ClerkUICtor}});if(!Clerk.isSignedIn){setGate('Duhet të hysh në llogarinë e administratorit për të vazhduar.');const b=document.createElement('button');b.id='clerkLogin';b.className='primary full';b.style.marginTop='14px';b.textContent='Hyr / Regjistrohu';$('clerkGate').querySelector('.login-card').append(b);b.onclick=()=>Clerk.openSignIn({fallbackRedirectUrl:'/admin.html'});return}const email=(Clerk.user?.primaryEmailAddress?.emailAddress||'').toLowerCase();if(email!==ADMIN_EMAIL){setGate('Kjo llogari nuk ka qasje në panelin e administratorit.');return}setGate('Qasje e autorizuar.',true);if(key)showApp()}catch(e){setGate(e.message||'Clerk nuk mund të inicializohet.')}}
function showApp(){ $('login').hidden=true;$('app').hidden=false;load() }
$('loginBtn').onclick=()=>{key=$('key').value.trim();if(!key)return;$('loginBtn').disabled=true;load(true).finally(()=>{$('loginBtn').disabled=false})};
async function load(fromLogin=false){try{const r=await fetch('/api/site-settings',{cache:'no-store'});settings=await r.json()||{seo:{},site:{}};settings.site=settings.site||{};sessionStorage.setItem('site-admin-key',key);if(fromLogin){showApp();return}bindMeta();bindSite();await waitFrame();items=frame.contentWindow.SiteContent?.collect?.()||[];mergeSaved();render();$('status').textContent=`Sanity · ${items.length} elemente`;if(!settings.contentItems?.length&&items.length)$('status').textContent=`Sanity · ${items.length} elemente · gati per import`;}catch(e){$('status').textContent='Nuk u ngarkua përmbajtja.'}}
function waitFrame(){return new Promise(resolve=>{if(frame.contentDocument?.readyState==='complete'&&frame.contentWindow.SiteContent)return resolve();frame.addEventListener('load',resolve,{once:true})})}
function mergeSaved(){const saved=new Map((settings.contentItems||[]).map(i=>[i.key,i]));items=items.map(i=>saved.has(i.key)?{...i,value:saved.get(i.key).value,label:saved.get(i.key).label||i.label,section:saved.get(i.key).section||i.section}:i)}
function bindMeta(){const s=settings.seo||{};$('seoTitle').value=s.title||'';$('seoDescription').value=s.description||'';$('canonical').value=s.canonicalUrl||'';$('ogTitle').value=s.ogTitle||'';$('ogDescription').value=s.ogDescription||'';$('twitterTitle').value=s.twitterTitle||'';$('twitterDescription').value=s.twitterDescription||''}
function bindSite(){const s=settings.site||{};$('siteName').value=s.name||'';$('sitePhone').value=s.phone||'';$('siteEmail').value=s.email||'';$('siteAddress').value=s.address||s.location||'';$('siteMapUrl').value=s.mapUrl||''}
function updatePreview(){frame.contentWindow.SiteContent?.apply?.({...settings,contentItems:items})}
function render(){const q=($('search').value||'').toLowerCase();const box=$('fields');box.replaceChildren();items.forEach((item,i)=>{if(q&&!`${item.label} ${item.section} ${item.value}`.toLowerCase().includes(q))return;const wrap=document.createElement('div');wrap.className='field';const label=document.createElement('label');label.textContent=item.label||item.key;const sec=document.createElement('span');sec.className='section';sec.textContent=item.section||'global';label.append(sec);const area=document.createElement('textarea');area.value=item.value||'';area.dataset.i=i;area.addEventListener('input',()=>{items[i].value=area.value;updatePreview()});wrap.append(label,area);box.append(wrap)});$('count').textContent=`${items.length} fusha`}
$('search').addEventListener('input',render);['seoTitle','seoDescription','canonical','ogTitle','ogDescription','twitterTitle','twitterDescription'].forEach(id=>$(id).addEventListener('input',()=>{settings.seo=settings.seo||{};const map={seoTitle:'title',seoDescription:'description',canonical:'canonicalUrl',ogTitle:'ogTitle',ogDescription:'ogDescription',twitterTitle:'twitterTitle',twitterDescription:'twitterDescription'};settings.seo[map[id]]=$(id).value;updatePreview()}));
['siteName','sitePhone','siteEmail','siteAddress','siteMapUrl'].forEach(id=>$(id).addEventListener('input',()=>{settings.site=settings.site||{};const map={siteName:'name',sitePhone:'phone',siteEmail:'email',siteAddress:'address',siteMapUrl:'mapUrl'};settings.site[map[id]]=$(id).value;if(id==='sitePhone'&&!settings.site.whatsappUrl)settings.site.whatsappUrl=`https://wa.me/${settings.site.phone.replace(/\D/g,'')}`;updatePreview()}));
async function saveToSanity(){const btn=$('saveBtn');btn.disabled=true;btn.textContent='Po ruhet…';try{const payload={seo:settings.seo||{},site:settings.site||{},contentItems:items};const r=await fetch('/api/admin-site-settings',{method:'POST',headers:{'Content-Type':'application/json','x-admin-key':key},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Save failed');settings.contentItems=items;localStorage.setItem('site-settings-saved',Date.now());$('status').textContent=`✓ U ruajt në Sanity · ${items.length} fusha`;}catch(e){$('status').textContent=e.message==='Unauthorized'?'ADMIN_KEY i gabuar ose mungon në Vercel.':`Gabim: ${e.message}`}finally{btn.disabled=false;btn.textContent='Ruaj në Sanity'}}
$('importBtn').onclick=async()=>{items=frame.contentWindow.SiteContent?.collect?.()||[];render();updatePreview();$('status').textContent=`U importuan ${items.length} elemente. Po ruhen në Sanity…`;if(key&&items.length)await saveToSanity()};$('saveBtn').onclick=saveToSanity;
frame.addEventListener('load',()=>{setTimeout(async()=>{if(!$('app').hidden){items=frame.contentWindow.SiteContent?.collect?.()||items;mergeSaved();render();updatePreview();if(key&&!settings.contentItems?.length&&items.length)await saveToSanity()}},250)});
initClerk();
})();
