(()=>{
const API='/api/site-settings';const SKIP=new Set(['SCRIPT','STYLE','NOSCRIPT','TEMPLATE','SVG']);
const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
function path(el){const a=[];let n=el;while(n&&n.nodeType===1&&n!==document.body){let i=1,s=n.previousElementSibling;while(s){if(s.tagName===n.tagName)i++;s=s.previousElementSibling}a.unshift(`${n.tagName.toLowerCase()}:nth-of-type(${i})`);n=n.parentElement}return`body>${a.join('>')}`}
function key(node,type,attr=''){const p=node.parentElement||node,s=Array.from(p.childNodes),i=Math.max(0,s.indexOf(node));return`${path(p)}|${type}|${i}|${attr}`}
function section(el){const s=el?.closest('section,header,footer');return s?.id||s?.className?.toString().split(' ')[0]||'global'}
function collect(){const items=[],seen=new Set(),w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){const p=n.parentElement,v=clean(n.nodeValue);if(!p||!v||SKIP.has(p.tagName)||p.closest('[data-cms-ignore]')||p.matches('.sr-only'))continue;const k=key(n,'text');if(seen.has(k))continue;seen.add(k);items.push({key:k,label:v.slice(0,90),section:section(p),kind:'text',attribute:'',value:v})}document.querySelectorAll('img,a,input,textarea,button,[aria-label],[title]').forEach(el=>{const attrs=el.tagName==='IMG'?['alt']:el.tagName==='A'?['aria-label','title','href']:['aria-label','title','placeholder'];attrs.forEach(attr=>{if(!el.hasAttribute(attr))return;const v=clean(el.getAttribute(attr));if(!v||(attr==='href'&&v.startsWith('#')))return;const k=key(el,'attribute',attr);if(seen.has(k))return;seen.add(k);items.push({key:k,label:`${el.tagName.toLowerCase()} ${attr}`,section:section(el),kind:'attribute',attribute:attr,value:v})})});return items}
function apply(settings){const values=new Map((settings?.contentItems||[]).map(i=>[i.key,i.value]));if(!values.size)return;const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){const p=n.parentElement;if(!p||SKIP.has(p.tagName)||p.closest('[data-cms-ignore]'))continue;const k=key(n,'text');if(values.has(k))n.nodeValue=values.get(k)}document.querySelectorAll('img,a,input,textarea,button,[aria-label],[title]').forEach(el=>{const attrs=el.tagName==='IMG'?['alt']:el.tagName==='A'?['aria-label','title','href']:['aria-label','title','placeholder'];attrs.forEach(attr=>{const k=key(el,'attribute',attr);if(values.has(k))el.setAttribute(attr,values.get(k))})});const seo=settings.seo||{};if(seo.title)document.title=seo.title;if(seo.description)document.querySelector('meta[name="description"]')?.setAttribute('content',seo.description);if(seo.ogTitle)document.querySelector('meta[property="og:title"]')?.setAttribute('content',seo.ogTitle);if(seo.ogDescription)document.querySelector('meta[property="og:description"]')?.setAttribute('content',seo.ogDescription);if(seo.twitterTitle)document.querySelector('meta[name="twitter:title"]')?.setAttribute('content',seo.twitterTitle);if(seo.twitterDescription)document.querySelector('meta[name="twitter:description"]')?.setAttribute('content',seo.twitterDescription);if(seo.canonicalUrl)document.querySelector('link[rel="canonical"]')?.setAttribute('href',seo.canonicalUrl);document.documentElement.dataset.siteContent='ready';document.dispatchEvent(new CustomEvent('site-content:ready',{detail:settings}))}
window.SiteContent={collect,apply};fetch(API,{headers:{Accept:'application/json'},cache:'no-store'}).then(r=>r.ok?r.json():null).then(apply).catch(()=>{});
})();
